
# Server Software descriptor

fields:
    create_date:        datetime=sqlDatetime()
    create_ip:          ip=clientIP()
    create_user_id:     ref(user)=userID()
    
    slug:               slug(name)
    name:               string(2, 100)
    version:            string(1, 20)[nullable]
    file_url:           url
#    file_id:            ref(file)=0
    image_id:           ref(file)=0
    published:          boolean=false
    installer_path:     string(2, 100)[nullable]
    starter_path:       string(2, 100)

indexes:
     - INDEX(slug)
     - FULLTEXT(name)
     