

http:
    delayedpage:
        path: "/delayedpage/{slug:page}.html"
        controller: "DelayedPageController"
        
#    home:
#        path: "/path/in/array/config"
#        method: "POST|GET"
#        method: "GET"
#        controller: "HomeController"
#    home2: "/path/with/all/methods->HomeController"
#    home3: "POST(/path/for/POST/method)->HomeController"
    
